version: '3.4'
services:

 swat-intel:
   image: movieapi
   restart: always
   build: 
     context: .
     dockerfile: Dockerfile   
   working_dir: movieapi
   container_name: movieapi
   environment:
     TZ: America/Sao_paulo
     SPRING_BOOT_ENVIRONMENT: Production
   volumes:
     - ./movieapi
     - ~/.m2:/root/.m2
   ports:
     - "8080:8080"
   command: mvn clean spring-boot:run
